### PR TITLE
Makefile: small portability and usability fixes

### PR DESCRIPTION
**Pull request by tripleee**
* clean: Don't use Bash syntax

### CODE REVIEW

**Comment by daylinmorgan** [comment]
If you'd like to see this merged please rebase on `main` and address the above comments.

**Comment by tripleee** [comment]
I'm sorry, I don't see any comments? I rebased it last week and no further rebase seems to be necessary.

**Comment by daylinmorgan** [comment]
@tripleee apologies I thought I already "submitted" the review comments but they were still pending. 

There is still merge conflicts with main so you'll need to rebase again. I only see this [merge commit](https://github.com/daylinmorgan/viv/pull/13/commits/82ac49d20b648c70718e6322b17fa3fd05b9540b).

**Comment by tripleee** [comment]
So, just the braces? (-: Fine - updated and rebased.

**Pull request merged**
